### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by roronoa6** [merrycodes/Office-E5#1]
## 感谢大佬的开源分享，今天运行时报如下错误，望解决，谢谢
![image](https://user-images.githubusercontent.com/42757522/121672611-95d33a80-cae2-11eb-82e7-350ef29945c4.png)

**Comment by merrycodes** [comment]
详细说明一下，是直接 Fork 过去运行的吗？（运行环境说一下）刚刚自测没有出现问题。查看[在GitHub仓库中添加 secrets](https://github.com/merrycodes/Office-E5#%E5%9C%A8github%E4%BB%93%E5%BA%93%E4%B8%AD%E6%B7%BB%E5%8A%A0-secrets)。

**Comment by roronoa6** [comment]
你好，我是fork过去运行的，各项配置无误，配置运行我在好几天前就已经配置好了当时可以运行，但是今天在我部署oneindex后再运行您的项目就报这样的错了？难道部署了oneindex，您的项目要用AZ上oneindex的id和secrest?

**Comment by merrycodes** [comment]
没有了解过 `OneIndex`，这个项目的参数需要与 `Azure`  中申请的应用程序中相关参数一致，并且要有对应的权限。建议重新新建一个专门用来跑该项目的应用程序，不要和 `OneIndex` 使用同一个应用程序（如果不是同一个，删掉之前的再新建试试），这种一般不是代码问题。

**Comment by roronoa6** [comment]
好的，我现在去看看

**Comment by roronoa6** [comment]
我似乎知道了什么，难道是因为设置了```Authenticator```?
![image](https://user-images.githubusercontent.com/42757522/121687327-cd4ae280-caf4-11eb-95bb-f366ca8013fe.png)

**Comment by merrycodes** [comment]
可能是这个的原因，我没有开启这个。

**Comment by roronoa6** [comment]
确定是开了双重验证导致

**Comment by shentam** [comment]
双重验证这个怎么解决？关闭双重验证还是有其他办法？

**Comment by merrycodes** [comment]
> 双重验证这个怎么解决？关闭双重验证还是有其他办法？

个人没有开启双重验证，可以尝试关闭双重验证试试看。

**Comment by merrycodes** [comment]
> 双重验证这个怎么解决？关闭双重验证还是有其他办法？

本人没有开启双重验证，可以尝试关闭双重验证试试看。
