### ISSUE TITLE
出現這錯誤是哪邊有問題

### ISSUE THREAD

**Issue by polo871209** [merrycodes/Office-E5#11]
OAuthProblemException{error='invalid_grant', description='AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
<img width="1112" alt="image" src="https://github.com/merrycodes/Office-E5/assets/95681896/941f9123-81b1-465d-8cc6-d46d40f2e3a6">

**Comment by merrycodes** [comment]
貌似需要账号开启双重验证来访问资源，但是我并没开启双重认证，可以尝试新建新的应用

**Comment by ModChino** [comment]
> OAuthProblemException{error='invalid_grant', description='AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. <img alt="image" width="1112" src="https://user-images.githubusercontent.com/95681896/239715780-941f9123-81b1-465d-8cc6-d46d40f2e3a6.png">
可以前往
Azure Active Directory --> 左侧下面属性 --> 点击最下面的“管理安全默认值” --> 禁用 --> 保存
即可
