### ISSUE TITLE
401报错

### ISSUE THREAD

**Issue by PantsuMeow** [merrycodes/Office-E5#12]
大佬我严格按照教程搭建，运行后是这样的
![image](https://github.com/merrycodes/Office-E5/assets/133024060/44bc3522-09d3-4308-b719-4a2d7cb019c9)
![image](https://github.com/merrycodes/Office-E5/assets/133024060/be706de0-c49b-4840-94c2-a4d8ec457a62)
重新在GitHub创建令牌后运行还是这样的，请问如何解决。
辛苦大佬

**Comment by merrycodes** [comment]
这个可能是 Microsoft 账号密码错误，在确认一下账号密码是否正确

**Comment by PantsuMeow** [comment]
已检查，还是报错:(
我又注册了个E5账号重新搭建后还是一样的结果

**Comment by PantsuMeow** [comment]
已检查，还是报错 :(
![image](https://github.com/merrycodes/Office-E5/assets/133024060/0d0d4f22-f6d0-4cc9-a6ab-7096bd679476)
![image](https://github.com/merrycodes/Office-E5/assets/133024060/668c6ec0-a834-4619-a729-fa13dbd8781c)
请问如何解决多重认证？是将其关闭即可？
谢谢大佬

**Comment by PantsuMeow** [comment]
已检查，还是报错:(
[5_Run jar.txt](https://github.com/merrycodes/Office-E5/files/11581868/5_Run.jar.txt)
![image](https://github.com/merrycodes/Office-E5/assets/133024060/a793291e-5e8a-4b40-a663-ccef324a3086)
貌似是需要双重认证，但我并不知道如何操作，是关闭双重认证即可吗？
谢谢大佬

**Comment by merrycodes** [comment]
关闭双重认证应该就可以，好像是在 `Azure` 中的 `租户属性` 里关闭双重认证的。 [链接](https://portal.azure.com/#view/Microsoft_AAD_IAM/TenantPropertiesBlade)，点击最下方的 `管理安全默认值`，选择 `已禁用`
![image](https://github.com/merrycodes/Office-E5/assets/48670688/504d9c20-51b2-451c-b4d8-ece9d6ba0e04)

**Comment by PantsuMeow** [comment]
![image](https://github.com/merrycodes/Office-E5/assets/133024060/21542a71-4eef-4c24-bafd-ac59add86114)
push又报错了

**Comment by merrycodes** [comment]
这可能是 `GitHub Token`  配置错误导致的，可以尝试重新获取新的  `Token`。如果不需要提交日志，也可以修改 `main.yml`，把提交日志相关删除。

**Comment by PantsuMeow** [comment]
![image](https://github.com/merrycodes/Office-E5/assets/133024060/2e268924-9b2b-40f8-883f-2522ecd0e11d)
删掉token终于成功了！！ :)
应该没什么影响吧...
总之辛苦大佬了！！

**Comment by gptbert** [comment]
> 这可能是 `GitHub Token` 配置错误导致的，可以尝试重新获取新的 `Token`。如果不需要提交日志，也可以修改 `main.yml`，把提交日志相关删除。

在`setting`-`Actions`-`General`里`Workflow permissions`选择“Read and write permissions”权限，否则push log会失败

**Comment by stianchen** [comment]
![image](https://github.com/merrycodes/Office-E5/assets/89346060/4d7cf93f-31c7-4441-b08b-a8da14446e10)
![image](https://github.com/merrycodes/Office-E5/assets/89346060/133f5df8-e272-42d3-81df-62428256cec4)

大佬您好！
我这里和一楼遇到了类似的问题：401报错。
我已经进行了更新账号密码、关闭双重验证、更新token等措施
但目前还是这样报错，请问能指导下如何解决吗？
辛苦您！

**Comment by merrycodes** [comment]
> ![image](https://user-images.githubusercontent.com/89346060/258273417-4d7cf93f-31c7-4441-b08b-a8da14446e10.png) ![image](https://user-images.githubusercontent.com/89346060/258273606-133f5df8-e272-42d3-81df-62428256cec4.png)
> 
> 大佬您好！ 我这里和一楼遇到了类似的问题：401报错。 我已经进行了更新账号密码、关闭双重验证、更新token等措施 但目前还是这样报错，请问能指导下如何解决吗？ 辛苦您！

看了一下你的报错信息 [invalid_request](https://login.microsoftonline.com/error?code=900023)，可能要看看 Azure 里面一些配置是否复制正确正确 [相关配置](https://github.com/merrycodes/Office-E5#%E5%9C%A8github%E4%BB%93%E5%BA%93%E4%B8%AD%E6%B7%BB%E5%8A%A0-secrets)

**Comment by stianchen** [comment]
![image](https://github.com/merrycodes/Office-E5/assets/89346060/8c213d61-894c-4160-b57d-57bce23e03e4)
重新建了一个Azure应用，解决问题了，谢谢大佬

**Comment by stianchen** [comment]
![image](https://github.com/merrycodes/Office-E5/assets/89346060/8c213d61-894c-4160-b57d-57bce23e03e4)
重新建了一个Azure应用，解决问题了，谢谢大佬
