### ISSUE TITLE
大佬看看这是什么问题

### ISSUE THREAD

**Issue by HWyyds** [merrycodes/Office-E5#14]
按着教程操作，跑actions时出现了这个报错，请问如何解决？
<img width="1293" alt="Screen Shot 2023-06-18 at 6 17 05 PM" src="https://github.com/merrycodes/Office-E5/assets/78462429/93a41edd-9d04-4f41-9e0b-8dc6eb09f293">

**Comment by merrycodes** [comment]
可以参考这个 https://github.com/merrycodes/Office-E5/issues/12#issuecomment-1595660452

**Comment by HWyyds** [comment]
已解决，谢谢大佬
