### ISSUE TITLE
自动运行时间的疑问

### ISSUE THREAD

**Issue by Castle0fGlass** [merrycodes/Office-E5#15]
```
cron: '0 0/6 15 1/2 ?'
```
请问这个cron的定时含义是什么呢？我这边action除了star执行以外没有定时执行过。

**Comment by merrycodes** [comment]
大概意思从一月到十二月，每两个月（1，3，5，7，9...）在月中的第15天，从0点开始每6个小时运行一次。具体可以查看官方文档[schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)，可以根据自己的需要调整定时任务

**Comment by Castle0fGlass** [comment]
> 大概意思从一月到十二月，每两个月（1，3，5，7，9...）在月中的第15天，从0点开始每6个小时运行一次。具体可以查看官方文档[schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)，可以根据自己的需要调整定时任务
> 
> 
> 
> 

懂了，感谢！
