### ISSUE TITLE
无法正常运行 action

### ISSUE THREAD

**Issue by iamalexblue** [merrycodes/Office-E5#2]
在开始前有看 issue 中说开了两步验证之后无法正常运行，于是我配置完成之后还特意关闭了两步验证，但是依然无法运行，不知道是什么原因，如果开发者有时间的话还望拨冗解答一下，多谢啦

**Comment by merrycodes** [comment]
具体的报错信息是什么？如果在 action 中无法通过的话，建议在本地调试一下。

**Comment by iamalexblue** [comment]
抱歉我是个编程小白，没什么水平，就是套着大佬的代码拿来用，不太明白如何本地调试，不过我刚看了报错显示 
```
Error: Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
```
好像是验证信息有问题

**Comment by merrycodes** [comment]
附一下 action 报错截图，正常来说按着 [README.md](https://github.com/merrycodes/Office-E5/blob/main/README.md) 操作没啥问题。

**Comment by iamalexblue** [comment]
![](https://cdn.jsdelivr.net/gh/iamalexblue/jsDelivrCDN@master/1649430049011uTools_1649429906147.png)

**Comment by iamalexblue** [comment]
还有之前忘了强调的一点是：您所写的 readme.md 中描述的客户端密码截止期限已经没有永久的设置选项了，最长只能设置两年，这个应该不会有影响吧？

![](https://cdn.jsdelivr.net/gh/iamalexblue/jsDelivrCDN@master/16494302446891649430243871.png)

**Comment by merrycodes** [comment]
客户端密码截至期限应该不影响，目测可能是 `TENANT_GUID` 的错误，重新设置一下 GitHub Secrets，还是不可以尝试重新创建 Azure 应用
