### ISSUE TITLE
cron任务未正常运行

### ISSUE THREAD

**Issue by MuelNova** [merrycodes/Office-E5#3]
![image](https://user-images.githubusercontent.com/68760718/162631001-90605229-9279-40d2-ae2e-eaad0eda3163.png)
观察`main.yml`看到存在cron任务
```
  schedule:
    - cron: '0 0/6 15 1/2 ?'
```
但是由于未知原因workflow未运行

**Comment by MuelNova** [comment]
> ![image](https://user-images.githubusercontent.com/68760718/162631001-90605229-9279-40d2-ae2e-eaad0eda3163.png) 观察`main.yml`看到存在cron任务
> 
> ```
>   schedule:
>     - cron: '0 0/6 15 1/2 ?'
> ```
> 
> 但是由于未知原因workflow未运行

以上均为手动执行

**Comment by merrycodes** [comment]
每两个月的第十五天每六小时运行一次

**Comment by MuelNova** [comment]
> 每两个月的第十五天每六小时运行一次

原来秒可以省略的啊...我一直以为是每隔两天15点每6分钟运行一次...

**Comment by MuelNova** [comment]
查了一下原来是Github Action不支持秒级的，理解了。

**Comment by merrycodes** [comment]
对的，`GitHub Action` 最低支持每五分钟一次
