### ISSUE TITLE
怎么测试啊

### ISSUE THREAD

**Issue by CN-Patrick** [merrycodes/Office-E5#8]
按照步骤都做下来了，不知道怎么看是否可以续订啊

**Comment by merrycodes** [comment]
如果 Actions 运行没有问题，那么就先过段时间，一般微软会发邮件给你

**Comment by CN-Patrick** [comment]
我在action里面看到有问题，有两个call api的错误，一个警告。怎么办大神

**Comment by CN-Patrick** [comment]
我按步骤重搞了一遍，这次是完全一致的，有一个警告，还是不行[Call-APi](https://github.com/CN-Patrick/Office-E5/actions/runs/4720965621/jobs/8373669816)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: zcong1993/setup-timezone@v1.1.1, actions/checkout@v2, actions/setup-java@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by merrycodes** [comment]
调用API已经成功，上传日子到仓库失败。查看一下GitHub相关配置是否正确，例如Token的权限是否给正确等
